[phases.setup]
nixPkgs = ["python311", "gcc", "gfortran", "binutils", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[build]
builder = "NIXPACKS"
